<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="runtimes\**\*"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest">
      <PackagePath>runtimes\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FreeTypeSharp" Version="3.1.0" />
  </ItemGroup>

</Project>
