<Project>
  <PropertyGroup>
    <Authors>SynesthesiaDev</Authors>
    <RepositoryUrl>https://github.com/SynesthesiaDev/Synesthesia</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <LangVersion>latestmajor</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md"
          Pack="true"
          PackagePath="\"
          Link="README.md" />
  </ItemGroup>
</Project>
