<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*"/>
    <EmbeddedResource Remove="bin\**;obj\**;*.csproj;*.cs"/>
  </ItemGroup>

</Project>
