<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Common</RootNamespace>

    <IsPackable>true</IsPackable>
    <PackageId>Synesthesia.Common</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    <PackageReference Include="Pastel" Version="7.0.1"/>
    <PackageReference Include="SynesthesiaDev.Codon.Codon" Version="2026.220.5" />
    <PackageReference Include="SynesthesiaUtils" Version="1.2.0"/>
  </ItemGroup>

</Project>
