using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Synesthesia.SourceGenerators;

[Generator]
public class ShaderSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect ALL shader files into a single collection
        var shaderFiles = context.AdditionalTextsProvider
            .Where(file =>
                file.Path.EndsWith(".vert") ||
                file.Path.EndsWith(".frag") ||
                file.Path.EndsWith(".vs") ||
                file.Path.EndsWith(".fs"))
            .Collect(); // This creates ImmutableArray<AdditionalText>

        // Register ONCE for the entire collection
        context.RegisterSourceOutput(shaderFiles, GenerateShaderSources);
    }

    private void GenerateShaderSources(
        SourceProductionContext context,
        ImmutableArray<AdditionalText> files)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated from {files.Length} shader file(s)");

        foreach (var file in files)
        {
            sb.AppendLine($"// - {Path.GetFileName(file.Path)}");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Synesthesia.Engine.Graphics.Shaders");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ShaderSources");
        sb.AppendLine("    {");

        // Process ALL files in ONE loop
        foreach (var file in files)
        {
            var fileName = Path.GetFileName(file.Path);
            var content = file.GetText(context.CancellationToken)?.ToString() ?? "";

            if (string.IsNullOrWhiteSpace(content))
            {
                sb.AppendLine($"        // WARNING: {fileName} is empty!");
                continue;
            }

            var identifier = makeIdentifier(fileName);
            var escaped = content.Replace("\"", "\"\"");

            sb.AppendLine($"        public const string {identifier} = @\"{escaped}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Add ONLY ONE source file with ALL constants
        context.AddSource("ShaderSources.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string makeIdentifier(string fileName)
    {
        // "default.frag" -> "DefaultFragment"
        var nameWithoutExt = Path.GetFileNameWithoutExtension(fileName);
        var extension = Path.GetExtension(fileName).TrimStart('.');

        var extSuffix = extension.ToLowerInvariant() switch
        {
            "vert" or "vs" => "Vertex",
            "frag" or "fs" => "Fragment",
            "geom" or "gs" => "Geometry",
            "comp" or "cs" => "Compute",
            _ => extension.ToUpperInvariant()
        };

        var baseName = toPascalCase(nameWithoutExt);
        return $"{baseName}{extSuffix}";
    }

    private static string toPascalCase(string input)
    {
        var sb = new StringBuilder();
        bool capitalize = true;

        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalize ? char.ToUpper(c) : c);
                capitalize = false;
            }
            else
            {
                capitalize = true;
            }
        }

        return sb.ToString();
    }
}
