<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework></TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IsPackable>true</IsPackable>
    <PackageId>Synesthesia.Engine</PackageId>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Synesthesia.Common\Synesthesia.Common.csproj"/>
    <ProjectReference Include="..\Synesthesia.Resources\Synesthesia.Resources.csproj"/>
    <ProjectReference Include="..\Synesthesia.NativeLibs\Synesthesia.NativeLibs.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    <PackageReference Include="ManagedBass" Version="4.0.2"/>
    <PackageReference Include="ManagedBass.Fx" Version="4.0.2"/>
    <PackageReference Include="ManagedBass.Mix" Version="4.0.2"/>
    <PackageReference Include="ManagedBass.Wasapi" Version="4.0.2"/>
    <PackageReference Include="SynesthesiaDev.Codon.IniTranscoder" Version="2026.220.5" />
    <PackageReference Include="SynesthesiaDev.Raylib-cs" Version="2026.307.0" />
  </ItemGroup>

</Project>
